---
title: "90's Music Canon"
author: "Ryan Harvey and Max Narvaez"
date: "9/29/2020"
output:
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

rec <- read_csv("time_series_90s_july13.csv") %>%
    select(-`11`:-`34`)
generation.rec.data <- read_csv("lollipop_chart_data_july_13.csv")

# Helpers
flip_sign <- function(l) {
     l <- as.numeric(l)*(-1)
     parse(text=l)
}

last_non_na_value <- function(r) {
    cols <- length(r)
    col <- cols - 1
    while (is.na(r[col])) {
        col <- col - 1
    }
    r[col]
}

# Prepare Dataset
x <- nrow(rec)
while (x > 0) {
  y <- 25
  while (y > 1) {
    if (rec[x, y] == 0) {
      rec[x, y] <- NA
      y <- y - 1
    } else {
      break
    }
  }
  x <- x - 1
}
```

## Recognition of Top 90's Songs by Age

```{r, echo=FALSE, message=FALSE}
rec %>%
    filter(`-13` >= .9) %>%
    pivot_longer(`-13`:`10`,
                 names_to = "generation", values_to = "recognition") %>%
    transmute(song = artist_song, generation = generation, recognition = recognition) %>%
    filter(!is.na(recognition)) %>%
    ggplot() +
    geom_line(aes(x = as.numeric(generation), recognition, color = song)) +
    geom_smooth(aes(as.numeric(generation), recognition), color = "black") +
    scale_x_continuous(breaks = seq(-13, 10, by = 1), labels = flip_sign) +
    theme(legend.position = "none") +
    labs(x = "Age in year that song was released",
         y = "% of people who know song")
```

## The Top-5 and Bottom-5 90's Songs by Current Popularity

```{r, echo=FALSE, message=FALSE}
current.rec <- rec %>%
    rowwise() %>%
    transmute(artist_song = artist_song,
              latest.recognition = last_non_na_value(c(`-13`, `-12`, `-11`, `-10`, `-9`, 
                                                       `-8`, `-7`, `-6`, `-5`, `-4`,
                                                       `-3`, `-2`, `-1`, `0`, `1`,
                                                       `2`, `3`, `4`, `5`, `6`,
                                                       `7`, `8`, `9`, `10`))) %>%
    arrange(desc(latest.recognition))

top.bottom.5.songs <- union(head(current.rec, 5), tail(current.rec, 5)) %>%
    pull(artist_song)

rec %>%
    filter(artist_song %in% top.bottom.5.songs) %>%
    pivot_longer(`-13`:`10`,
                 names_to = "generation", values_to = "recognition") %>%
    transmute(song = artist_song, generation = generation, recognition = recognition) %>%
    filter(!is.na(recognition)) %>%
    ggplot() +
    geom_line(aes(x = as.numeric(generation), recognition, color = song)) +
    scale_x_continuous(breaks = seq(-13, 10, by = 1), labels = flip_sign) +
    theme(legend.position = "bottom", legend.direction = "vertical") +
    guides(color = guide_legend(ncol=2)) +
    labs(x = "Age in year that song was released",
         y = "% of people who know song",
         color = "Artist/Song")
```

## The Top-5 90's Songs That Were Quickly Forgotten

```{r, echo = FALSE, message=FALSE}
avg.table <- summarize_at(rec,
                          vars(`-13`:`10`),
                          ~ mean(., na.rm = TRUE))

avgs <- c()
avgs["-13"] = avg.table$`-13`
avgs["-12"] = avg.table$`-12`
avgs["-11"] = avg.table$`-11`
avgs["-10"] = avg.table$`-10`
avgs["-9"] = avg.table$`-9`
avgs["-8"] = avg.table$`-8`
avgs["-7"] = avg.table$`-7`
avgs["-6"] = avg.table$`-6`
avgs["-5"] = avg.table$`-5`
avgs["-4"] = avg.table$`-4`
avgs["-3"] = avg.table$`-3`
avgs["-2"] = avg.table$`-2`
avgs["-1"] = avg.table$`-1`
avgs["0"] = avg.table$`0`
avgs["1"] = avg.table$`1`
avgs["2"] = avg.table$`2`
avgs["3"] = avg.table$`3`
avgs["4"] = avg.table$`4`
avgs["5"] = avg.table$`5`
avgs["6"] = avg.table$`6`
avgs["7"] = avg.table$`7`
avgs["8"] = avg.table$`8`
avgs["9"] = avg.table$`9`
avgs["10"] = avg.table$`10`

low_songs <- rec %>%
    filter(`-13` >= .8) %>%
    pivot_longer(`-13`:`10`,
                 names_to = "generation", values_to = "recognition") %>%
    transmute(song = artist_song, generation = generation, recognition = recognition) %>%
    filter(!is.na(recognition)) %>%
    mutate(diff = recognition - avgs[as.character(generation)]) %>%
    group_by(song) %>%
    summarize(diff.from.trend = sum(diff)) %>%
    arrange(desc(diff.from.trend)) %>%
    tail(5) %>%
    pull(song)

rec %>%
    filter(artist_song %in% low_songs) %>%
    pivot_longer(`-13`:`10`,
                 names_to = "generation", values_to = "recognition") %>%
    transmute(song = artist_song, generation = generation, recognition = recognition) %>%
    filter(!is.na(recognition)) %>%
    ggplot() +
    geom_line(aes(x = as.numeric(generation), recognition, color = song)) +
    scale_x_continuous(breaks = seq(-13, 10, by = 1), labels = flip_sign) +
    theme(legend.position = "bottom", legend.direction = "vertical") +
    guides(color = guide_legend(ncol=2)) +
    labs(x = "Age in year that song was released",
         y = "% of people who know song",
         color = "Artist/Song")
```


## The Change in Recognition Across Different Generations

```{r, echo=FALSE, message=FALSE}
knitr::kable(head(arrange(generation.rec.data, 
                          desc(generation.rec.data$mean_gen_z_recognition)), 50),
             digits = 2,
             col.names = c("Artist/Song", "Millenial", "Gen Z"))
```

## Top 90's Songs That Were Less Recognized 

```{r, echo=FALSE, message=FALSE}
low_rec_at_release <- rec %>%
    filter(`-13` <= .5) %>%
    pivot_longer(`-13`:`10`,
                 names_to = "generation", values_to = "recognition") %>%
    transmute(song = artist_song, generation = generation, recognition = recognition) %>%
    filter(!is.na(recognition))

ggplot(low_rec_at_release) +
geom_line(aes(x = as.numeric(generation), recognition, color = song)) +
geom_smooth(aes(as.numeric(generation), recognition), color = "black") +
scale_x_continuous(breaks = seq(-13, 10, by = 1), labels = flip_sign) +
theme(legend.position = "none") +
labs(x = "Age in year that song was released",
     y = "% of people who know song")

low_rec_at_release %>%
    mutate(diff = recognition - avgs[as.character(generation)]) %>%
    group_by(song) %>%
    summarize(diff.from.trend = sum(diff)) %>%
    arrange(desc(diff.from.trend)) %>%
    head(5) %>%
    pull(song)
```


